name: Docker build-push

on:
  push:
    branches: [ master ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name:  Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.docker_user }}
        password: ${{ secrets.docker_pass }}
        repository: matsproesser/fiscal-de-pr
        tags: latest
        tag_with_ref: true
